# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               A L D A
tagline:             "Tech Evangelist & Engineer & Researcher"
description:         ""
url:                 https://edward0im.github.io
baseurl:            ''
paginate:            10

# About/contact
author:
  name:              Edward Gyubeom Im
  url:               https://edward0im.github.io
  email:             gyurse@gmail.com

# Disqus
discus-identifier: tigerk0430-github-io # add your discus identifier
  
# Custom vars
version:             1.0.0

plugins: ['jekyll-paginate','jekyll-sitemap']

# Tag setting
# collections:
#     mathematics:
#         output: true
#         matrix:
#             output: true

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

google_analytics:
  ua: 'UA-109898110-1'

github:
  repo: 'https://github.com/edward0im/edward0im.github.io'

category_dir: category/
tag_dir: tag/

excerpt_separator: ""
